# Generated by Django 4.2.2 on 2023-06-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='hhh', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='pers',
            field=models.CharField(choices=[('n', 'Физическое лицо'), ('l', 'Юридическое лицо')], max_length=1),
        ),
    ]
