# Generated by Django 4.2.2 on 2023-06-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_banner_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pers',
            field=models.CharField(choices=[('n', 'Физическое лицо'), ('l', 'Юридическое лицо')], max_length=1, verbose_name='юр/физ лицо'),
        ),
    ]
