# Generated by Django 4.2.2 on 2023-06-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_post_text_alter_service_pers'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='services.service'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='pers',
            field=models.CharField(choices=[('l', 'Юридическое лицо'), ('n', 'Физическое лицо')], max_length=1, verbose_name='юр/физ лицо'),
        ),
    ]
