# Generated by Django 4.2.2 on 2023-07-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_pers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='pers',
            field=models.CharField(choices=[('l', 'Юридическое лицо'), ('n', 'Физическое лицо')], max_length=1, verbose_name='юр/физ лицо'),
        ),
    ]
