# Generated by Django 4.2.2 on 2023-07-10 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_service_pers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AddField(
            model_name='client',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 10, 20, 43, 31, 295310), verbose_name='Дата и время обращения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='auto', max_length=50, verbose_name='Ф.И.О.'),
            preserve_default=False,
        ),
    ]
