# Generated by Django 4.2.2 on 2023-07-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_client_first_name_remove_client_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='pers',
            field=models.CharField(choices=[('l', 'Юридическое лицо'), ('n', 'Физическое лицо')], max_length=1, verbose_name='юр/физ лицо'),
        ),
    ]
